let collection = {
    new: 'new',
    textElem: 'TextElement',
    text1: '"Hola a todos"',
    text2: '"color-texto"',
    text3: '"hola cómo estas"',
    text4: '"Click aquí"',
    clss: 'class:',
    type: 'type:',
    _id: '"ID"',
    id: 'id:',
    row_id: '_row.id',
    name: 'name:',
    _name: '"Nombre"',
    _name_: '"name"',
    target: 'target:',
    alert: 'alert',
    arrow: ' => ',
    let: 'let',
    var: 'var',
    btnType: 'ButtonElementType',
    btn: 'ButtonElement',
    _btn: 'btn',
    customClass: '"custom-css"',
    salute: '"Saludos"',
    primary: 'Primary',
    div: 'DivElement',
    uno: '"Uno"',
    dos: '"Dos"',
    tres: '"Tres"',
    vstack: 'VStack',
    hstack: 'HStack',
    tbl: 'tbl',
    table: 'Table',
    str: 'string',
    header: 'header',
    sourceData: 'sourceData',
    data: 'data',
    row: '_row',
    title: 'title',
    return: 'return',
    comment: '// asigno valores a la tabla',
    selectElement: 'SelectElement',
    select: 'slct',
    tag: 'tag',
    model: 'model',
    buttonIcon: 'buttonIcon',
    iconDav: 'IconDav',
    genericIcon: 'GenericIcon',
    tagText: '"relationType"',
    titleText: '"Relación"',
    modelText: '"relation"',
    classRotate: '"icon-rotate"',
    classreflect: '"reflect-horizontal"',
    value: 'value',
    value1: '"Valor 1"',
    value2: '"Valor 2"',
    value3: '"Valor 3"',
    inpText: 'inpText',
    inpNumber: 'inpNumber',
    inputElement: 'InputElement',
    typeNumber: 'typeNumber',
    maxLength: 'maxLength',
    true: 'true',
    idNum: '"idNum"',
    numIden: '"Número de Identificación"',
    idText: '"idtext"',
    nombre: '"Nómbre"',
    get: function(name:string) {
        return this[name];
    }
}

let stylesClass: any = {
    new: "text-blue-500",
    textElem: "text-teal-400",
    text1: "text-red-300",
    text2: "text-red-300",
    text3: "text-red-300",
    text4: "text-red-300",
    clss: "text-cyan-300",
    type: "text-cyan-300",
    _id: 'text-red-300',
    id: "text-cyan-300",
    row_id: "text-cyan-300",
    name: "text-cyan-300",
    _name: "text-red-300",
    _name_: "text-red-300",
    target: "text-yellow-300",
    alert: "text-yellow-300",
    arrow: "text-blue-500",
    let: "text-blue-500",
    var: "text-blue-500",
    btn: "text-teal-400",
    _btn: "",
    btnType: "text-teal-400",
    customClass: "text-red-300",
    salute: "text-red-300",
    primary: "text-cyan-300",
    div: "text-teal-400",
    uno: "text-red-300",
    dos: "text-red-300",
    tres: "text-red-300",
    vstack: "text-yellow-300",
    hstack: "text-yellow-300",
    tbl: "text-cyan-300",
    table: "text-yellow-300",
    str: "text-teal-400",
    header: "text-cyan-300",
    data: "text-cyan-300",
    row: "text-cyan-300",
    title: "text-cyan-300",
    return: "text-purple-300",
    sourceData: "text-cyan-300",
    comment: "text-gray-400",
    selectElement: "text-teal-400",
    select: "text-cyan-300",
    tag: "text-cyan-300",
    model: "text-cyan-300",
    buttonIcon: "text-cyan-300",
    iconDav: "text-cyan-300",
    genericIcon: "text-teal-400",
    tagText: "text-red-300",
    titleText: "text-red-300",
    modelText: "text-red-300",
    classRotate: "text-red-300",
    classreflect: "text-red-300",
    value: "text-cyan-300",
    value1: "text-red-300",
    value2: "text-red-300",
    value3: "text-red-300",
    inpText: "text-cyan-300",
    inpNumber: "text-cyan-300",
    inputElement: "text-teal-400",
    typeNumber: "text-cyan-300",
    maxLength: "text-cyan-300",
    true: "text-blue-500",
    idNum: "text-red-300",
    numIden: "text-red-300",
    idText: "text-red-300",
    nombre: "text-red-300",
}

export {
    collection,
    stylesClass
}